### ISSUE TITLE
Problem using ifm_contrib in Feflow-ScriptingMenu

### ISSUE THREAD

**Issue by oyalex** [DHI/ifm_contrib#7]
Hi,
I'm working with Python 3.7 and Feflow 7.4.2.
So far I wrote a script in an external IDE, but now I want to bring it back into the integrated Scripting-Menu of Feflow.
According to the [documentation](http://www.feflow.info/html/help74/feflow/14_References/GUI/Menus/menu_scripting.html) I rewrote my code and removed the line `doc = ifm.loadDocument('myFile.fem')` too. As you may thought: There I got an error, hence ifm_contrib needs a defined file to load. So before I change something in the __init__.py and corrupt it all, I'm asking here.

The script should do something like set some boundary conditions, change their values and so on.
I tried using the 'Edit Script...' as well as the 'Execute Python Command' but both ways led to the same error message:

> from ifm37 import loadDocument as _loadDocumentImportError: cannot import name 'loadDocument' from 'ifm37' (unknown location)<class 'ImportError'>

Is there any possibility to execute my script using the internal scripting menu of Feflow, or is this just possible with the original ifm module?

Thanks,
Alex

**Comment by red5alex** [comment]
Hi, I am afraid that it is not possible to use ifm_contrib inside the FEFLOW scripting menu at this time, because FEFLOW will always import the standard ifm and load the doc-object from there. A workaround might be possible in the future, however this requires a change of the way the Python environments handles external Ptyon interpreters. This feature will not be release before FEFLOW 7.6, unfortunately.

**Comment by oyalex** [comment]
Okay, thank you for sharing this information. Saves a lot of time trying to solve this on my one.

**Comment by oyalex** [comment]
Hello again,
are there existing any new information about that problem, now as the new FEFLOW 7.6 version is available?
